image: dparra0007/docker:latest

services:
  - docker:dind

stages:
- build

variables:
  CONTAINER_SERVICE_IMAGE: dparra0007/userapi:$CI_RUNNER_ID
  CONTAINER_SERVICE_RELEASE_IMAGE: dparra0007/userapi:latest

  CONTAINER_DB_IMAGE: dparra0007/userapi-db:$CI_RUNNER_ID
  CONTAINER_DB_RELEASE_IMAGE: dparra0007/userapi-db:latest

  CONTAINER_APIGATEWAY_IMAGE: dparra0007/userapi-apigateway:$CI_RUNNER_ID
  CONTAINER_APIGATEWAY_RELEASE_IMAGE: dparra0007/userapi-apigateway:latest

  CONTAINER_DISCOVERY_IMAGE: dparra0007/userapi-discovery:$CI_RUNNER_ID
  CONTAINER_DISCOVERY_RELEASE_IMAGE: dparra0007/userapi-discovery:latest

before_script:
  - docker login -u $DOCKERHUB_USER -p $DOCKERHUB_PASS https://index.docker.io/v1/

#  - /usr/local/bin/oc login ${OC_URL} --token=${OC_TOKEN}
#  - /usr/local/bin/oc project userapi || /usr/local/bin/oc new-project userapi

build:
  stage: build
  script:
    - docker build --pull -t $CONTAINER_DISCOVERY_IMAGE ./userapi-discovery
    - docker push $CONTAINER_DISCOVERY_IMAGE
    - docker build --pull -t $CONTAINER_DISCOVERY_RELEASE_IMAGE ./userapi-discovery
    - docker push $CONTAINER_DISCOVERY_RELEASE_IMAGE

    - docker build --pull -t $CONTAINER_DB_IMAGE ./userapi-db
    - docker push $CONTAINER_DB_IMAGE
    - docker build --pull -t $CONTAINER_DB_RELEASE_IMAGE ./userapi-db
    - docker push $CONTAINER_DB_RELEASE_IMAGE

    - docker build --pull -t $CONTAINER_SERVICE_IMAGE ./userapi
    - docker push $CONTAINER_SERVICE_IMAGE
    - docker build --pull -t $CONTAINER_SERVICE_RELEASE_IMAGE ./userapi
    - docker push $CONTAINER_SERVICE_RELEASE_IMAGE

    - docker build --pull -t $CONTAINER_APIGATEWAY_IMAGE ./userapi-apigateway
    - docker push $CONTAINER_APIGATEWAY_IMAGE
    - docker build --pull -t $CONTAINER_APIGATEWAY_RELEASE_IMAGE ./userapi-apigateway
    - docker push $CONTAINER_APIGATEWAY_RELEASE_IMAGE