image: dparra0007/docker:451

services:
  - name: dparra0007/docker-dind:421
    alias: docker

stages:
- test code
- build docker
- deploy

variables:
  CONTAINER_SERVICE_IMAGE: dparra0007/userapi
  CONTAINER_DB_IMAGE: dparra0007/userapi-db
  CONTAINER_APIGATEWAY_IMAGE: dparra0007/userapi-apigateway
  CONTAINER_DISCOVERY_IMAGE: dparra0007/userapi-discovery

static_test_service:
  stage: test code
  script:
    - docker run --rm -v $(pwd):/data -w /data dparra0007/sonar-scanner:20171010-1 sonar-scanner
     -Dsonar.projectKey=$CI_PROJECT_NAMESPACE:$CI_PROJECT_NAME 
     -Dsonar.projectName=$CI_PROJECT_NAME 
     -Dsonar.branch=$CI_COMMIT_REF_NAME 
     -Dsonar.projectVersion=$CI_JOB_ID 
     -Dsonar.sources=./userapi 
     -Dsonar.gitlab.project_id=$CI_PROJECT_ID 
     -Dsonar.gitlab.commit_sha=$CI_COMMIT_SHA 
     -Dsonar.gitlab.ref_name=$CI_COMMIT_REF_NAME
  except:
    - triggers

build_service:
  stage: build docker
  script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.gitlab.com
    - docker build -t registry.gitlab.com/w53/w53-userapi/userapi ./userapi
    - docker tag registry.gitlab.com/w53/w53-userapi/userapi registry.gitlab.com/w53/w53-userapi/userapi:$CI_COMMIT_REF_NAME
    - docker push registry.gitlab.com/w53/w53-userapi/userapi:$CI_COMMIT_REF_NAME
  except:
    - triggers

build_discovery:
  stage: build docker
  script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.gitlab.com
    - docker build -t registry.gitlab.com/w53/w53-userapi/userapi-discovery ./userapi-discovery
    - docker tag registry.gitlab.com/w53/w53-userapi/userapi-discovery registry.gitlab.com/w53/w53-userapi/userapi-discovery:$CI_COMMIT_REF_NAME
    - docker push registry.gitlab.com/w53/w53-userapi/userapi-discovery:$CI_COMMIT_REF_NAME
  except:
    - triggers

build_db:
  stage: build docker
  script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.gitlab.com
    - docker build -t registry.gitlab.com/w53/w53-userapi/userapi-db ./userapi-db
    - docker tag registry.gitlab.com/w53/w53-userapi/userapi-db registry.gitlab.com/w53/w53-userapi/userapi-db:$CI_COMMIT_REF_NAME
    - docker push registry.gitlab.com/w53/w53-userapi/userapi-db:$CI_COMMIT_REF_NAME
  except:
    - triggers

build_apigateway:
  stage: build docker
  script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.gitlab.com
    - docker build -t registry.gitlab.com/w53/w53-userapi/userapi-apigateway ./userapi-apigateway
    - docker tag registry.gitlab.com/w53/w53-userapi/userapi-apigateway registry.gitlab.com/w53/w53-userapi/userapi-apigateway:$CI_COMMIT_REF_NAME
    - docker push registry.gitlab.com/w53/w53-userapi/userapi-apigateway:$CI_COMMIT_REF_NAME
  except:
    - triggers

deploy_staging_service:
  stage: deploy
  image: dparra0007/docker:448
  variables:
    IMG_BLD: "registry.gitlab.com/w53/w53-userapi/userapi:$CI_COMMIT_REF_NAME"
    PATH_DFILE: "./userapi/Dockerfile"
  script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.gitlab.com
    - docker pull registry.gitlab.com/w53/w53-userapi/userapi:$CI_COMMIT_REF_NAME
    - docker exec anchore anchore analyze --image registry.gitlab.com/w53/w53-userapi/userapi:$CI_COMMIT_REF_NAME
    - docker exec anchore anchore gate --image registry.gitlab.com/w53/w53-userapi/userapi:$CI_COMMIT_REF_NAME
    - docker tag registry.gitlab.com/w53/w53-userapi/userapi:$CI_COMMIT_REF_NAME $CONTAINER_SERVICE_IMAGE
    - docker tag registry.gitlab.com/w53/w53-userapi/userapi:$CI_COMMIT_REF_NAME $CONTAINER_SERVICE_IMAGE:$CI_PIPELINE_ID-$CI_JOB_ID
    - docker login -u $DOCKERHUB_USER -p $DOCKERHUB_PASS https://index.docker.io/v1/
    - docker push $CONTAINER_SERVICE_IMAGE
    - docker push $CONTAINER_SERVICE_IMAGE:$CI_PIPELINE_ID-$CI_JOB_ID
  environment:
    name: staging
  only:
    - master

deploy_staging_discovery:
  stage: deploy
  image: dparra0007/docker:448
  variables:
    IMG_BLD: "registry.gitlab.com/w53/w53-userapi/userapi-discovery:$CI_COMMIT_REF_NAME"
    PATH_DFILE: "./userapi-discovery/Dockerfile"
  script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.gitlab.com
    - docker pull registry.gitlab.com/w53/w53-userapi/userapi-discovery:$CI_COMMIT_REF_NAME
    - docker exec anchore anchore analyze --image registry.gitlab.com/w53/w53-userapi/userapi-discovery:$CI_COMMIT_REF_NAME
    - docker exec anchore anchore gate --image registry.gitlab.com/w53/w53-userapi/userapi-discovery:$CI_COMMIT_REF_NAME
    - docker tag registry.gitlab.com/w53/w53-userapi/userapi-discovery:$CI_COMMIT_REF_NAME $CONTAINER_DISCOVERY_IMAGE
    - docker tag registry.gitlab.com/w53/w53-userapi/userapi-discovery:$CI_COMMIT_REF_NAME $CONTAINER_DISCOVERY_IMAGE:$CI_PIPELINE_ID-$CI_JOB_ID
    - docker login -u $DOCKERHUB_USER -p $DOCKERHUB_PASS https://index.docker.io/v1/
    - docker push $CONTAINER_DISCOVERY_IMAGE
    - docker push $CONTAINER_DISCOVERY_IMAGE:$CI_PIPELINE_ID-$CI_JOB_ID
  environment:
    name: staging
  only:
    - master

deploy_staging_db:
  stage: deploy
  image: dparra0007/docker:448
  variables:
    IMG_BLD: "registry.gitlab.com/w53/w53-userapi/userapi-db:$CI_COMMIT_REF_NAME"
    PATH_DFILE: "./userapi-db/Dockerfile"
  script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.gitlab.com
    - docker pull registry.gitlab.com/w53/w53-userapi/userapi-db:$CI_COMMIT_REF_NAME
    - docker exec anchore anchore analyze --image registry.gitlab.com/w53/w53-userapi/userapi-db:$CI_COMMIT_REF_NAME
    - docker exec anchore anchore gate --image registry.gitlab.com/w53/w53-userapi/userapi-db:$CI_COMMIT_REF_NAME
    - docker tag registry.gitlab.com/w53/w53-userapi/userapi-db:$CI_COMMIT_REF_NAME $CONTAINER_DB_IMAGE
    - docker tag registry.gitlab.com/w53/w53-userapi/userapi-db:$CI_COMMIT_REF_NAME $CONTAINER_DB_IMAGE:$CI_PIPELINE_ID-$CI_JOB_ID
    - docker login -u $DOCKERHUB_USER -p $DOCKERHUB_PASS https://index.docker.io/v1/
    - docker push $CONTAINER_DB_IMAGE
    - docker push $CONTAINER_DB_IMAGE:$CI_PIPELINE_ID-$CI_JOB_ID
  environment:
    name: staging
  only:
    - master

deploy_staging_apigateway:
  stage: deploy
  image: dparra0007/docker:448
  variables:
    IMG_BLD: "registry.gitlab.com/w53/w53-userapi/userapi-apigateway:$CI_COMMIT_REF_NAME"
    PATH_DFILE: "./userapi-apigateway/Dockerfile"
  script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.gitlab.com
    - docker pull registry.gitlab.com/w53/w53-userapi/userapi-apigateway:$CI_COMMIT_REF_NAME
    - docker exec anchore anchore analyze --image registry.gitlab.com/w53/w53-userapi/userapi-apigateway:$CI_COMMIT_REF_NAME
    - docker exec anchore anchore gate --image registry.gitlab.com/w53/w53-userapi/userapi-apigateway:$CI_COMMIT_REF_NAME
    - docker tag registry.gitlab.com/w53/w53-userapi/userapi-apigateway:$CI_COMMIT_REF_NAME $CONTAINER_APIGATEWAY_IMAGE
    - docker tag registry.gitlab.com/w53/w53-userapi/userapi-apigateway:$CI_COMMIT_REF_NAME $CONTAINER_APIGATEWAY_IMAGE:$CI_PIPELINE_ID-$CI_JOB_ID
    - docker login -u $DOCKERHUB_USER -p $DOCKERHUB_PASS https://index.docker.io/v1/
    - docker push $CONTAINER_APIGATEWAY_IMAGE
    - docker push $CONTAINER_APIGATEWAY_IMAGE:$CI_PIPELINE_ID-$CI_JOB_ID
  environment:
    name: staging
  only:
    - master

deploy_prod:
  stage: deploy
  image: appropriate/curl
  script:
    - echo "Deploy to production server"
    - curl -X POST https://cloud.docker.com/api/app/v1/service/6d07ee88-1f5c-4e94-aee5-1934c4c36b7a/trigger/8b45491a-2f4b-4049-a194-2f607bb1e3aa/call/
    - curl -X POST https://cloud.docker.com/api/app/v1/service/2880a57f-e3da-47d3-8c88-7f9473751e25/trigger/19561cf4-9afe-4d0a-ae06-4cd104e1053b/call/
    - curl -X POST https://cloud.docker.com/api/app/v1/service/cdd0144d-fe0f-4079-8903-1c8d49d621d0/trigger/d72dde24-7983-4759-8b5c-e0cb04c91518/call/
    - curl -X POST https://cloud.docker.com/api/app/v1/service/947799be-0784-4d2c-8f55-20619fab7e15/trigger/2ea9b88a-ccd0-4802-8876-8fc2c661151c/call/
  environment:
    name: production
    url: http://userapi-apigateway.w53-userapi.947799be.svc.dockerapp.io:8080/userapi/swagger.json
  when: manual
  only:
    - master
  except:
    - triggers