image: docker:latest

services:
  - docker:dind

stages:
- build

variables:
  CONTAINER_SERVICE_IMAGE: dparra0007/userapi:$CI_RUNNER_ID
  CONTAINER_SERVICE_RELEASE_IMAGE: dparra0007/userapi:latest

  CONTAINER_DB_IMAGE: dparra0007/userapi-db:$CI_RUNNER_ID
  CONTAINER_DB_RELEASE_IMAGE: dparra0007/userapi-db:latest

before_script:
  - docker login -u $DOCKERHUB_USER -p $DOCKERHUB_PASS https://index.docker.io/v1/

build:
  stage: build
  script:
    - docker build -f userapi/Dockerfile --pull -t $CONTAINER_SERVICE_IMAGE .
    - docker push $CONTAINER_IMAGE
    - docker build -f userapi/Dockerfile --pull -t $CONTAINER_SERVICE_RELEASE_IMAGE .
    - docker push $CONTAINER_RELEASE_IMAGE