image: dparra0007/docker:latest

services:
  - docker:dind

stages:
- build
- deploy

variables:
  CONTAINER_SERVICE_IMAGE: dparra0007/userapi:$CI_RUNNER_ID
  CONTAINER_SERVICE_RELEASE_IMAGE: dparra0007/userapi:latest

  CONTAINER_DB_IMAGE: dparra0007/userapi-db:$CI_RUNNER_ID
  CONTAINER_DB_RELEASE_IMAGE: dparra0007/userapi-db:latest

  CONTAINER_APIGATEWAY_IMAGE: dparra0007/userapi-apigateway:$CI_RUNNER_ID
  CONTAINER_APIGATEWAY_RELEASE_IMAGE: dparra0007/userapi-apigateway:latest

  CONTAINER_DISCOVERY_IMAGE: dparra0007/userapi-discovery:$CI_RUNNER_ID
  CONTAINER_DISCOVERY_RELEASE_IMAGE: dparra0007/userapi-discovery:latest

before_script:
  - docker login -u $DOCKERHUB_USER -p $DOCKERHUB_PASS https://index.docker.io/v1/

  - /usr/local/bin/oc login ${OC_URL} --token=${OC_TOKEN}
  - /usr/local/bin/oc project userapi || /usr/local/bin/oc new-project userapi

build_service:
  stage: build
  script:
    - docker build --pull -t $CONTAINER_SERVICE_IMAGE ./userapi
    - docker push $CONTAINER_SERVICE_IMAGE
    - docker build --pull -t $CONTAINER_SERVICE_RELEASE_IMAGE ./userapi
    - docker push $CONTAINER_SERVICE_RELEASE_IMAGE

build_discovery:
  stage: build
  script:
    - docker build --pull -t $CONTAINER_DISCOVERY_IMAGE ./userapi-discovery
    - docker push $CONTAINER_DISCOVERY_IMAGE
    - docker build --pull -t $CONTAINER_DISCOVERY_RELEASE_IMAGE ./userapi-discovery
    - docker push $CONTAINER_DISCOVERY_RELEASE_IMAGE

build_db:
  stage: build
  script:
    - docker build --pull -t $CONTAINER_DB_IMAGE ./userapi-db
    - docker push $CONTAINER_DB_IMAGE
    - docker build --pull -t $CONTAINER_DB_RELEASE_IMAGE ./userapi-db
    - docker push $CONTAINER_DB_RELEASE_IMAGE

build_apigateway:
  stage: build
  script:
    - docker build --pull -t $CONTAINER_APIGATEWAY_IMAGE ./userapi-apigateway
    - docker push $CONTAINER_APIGATEWAY_IMAGE
    - docker build --pull -t $CONTAINER_APIGATEWAY_RELEASE_IMAGE ./userapi-apigateway
    - docker push $CONTAINER_APIGATEWAY_RELEASE_IMAGE

deploy_staging:
  stage: deploy
  script:
    - docker pull $CONTAINER_DISCOVERY_RELEASE_IMAGE
    - docker pull $CONTAINER_DB_RELEASE_IMAGE
    - docker pull $CONTAINER_SERVICE_RELEASE_IMAGE
    - docker pull $CONTAINER_APIGATEWAY_RELEASE_IMAGE
  environment:
    name: staging
    url: http://userapi-apigateway.userapi.d6e30f11.svc.dockerapp.io:8080/userapi/swagger.json
  only:
    - master
    
deploy_prod:
  stage: deploy
  script:
    - echo "Deploy to production server"
  environment:
    name: production
    url: https://example.com
  when: manual
  only:
    - master
