apiVersion: v1
items:
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    creationTimestamp: null
    labels:
      io.kompose.service: userapi-config-claim0
    name: userapi-config-claim0
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 100Mi
  status: {}
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    creationTimestamp: null
    labels:
      io.kompose.service: userapi-dynamic-config-claim0
    name: userapi-dynamic-config-claim0
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 100Mi
  status: {}
- apiVersion: v1
  kind: ImageStream
  metadata:
    creationTimestamp: null
    name: userapi
  spec:
    tags:
    - annotations:
        openshift.io/imported-from: dparra0007/userapi:{{TAG_SERVICE}}
      from:
        kind: DockerImage
        name: dparra0007/userapi:{{TAG_SERVICE}}
      generation: null
      importPolicy: {}
      name: "{{TAG_SERVICE}}"
  status:
    dockerImageRepository: ""
- apiVersion: v1
  kind: ImageStream
  metadata:
    creationTimestamp: null
    name: dparra0007-config
  spec:
    tags:
    - annotations:
        openshift.io/imported-from: iaghcp-docker-technical-architecture.jfrog.io/static-config:1.0.0
      from:
        kind: DockerImage
        name: iaghcp-docker-technical-architecture.jfrog.io/static-config:1.0.0
      generation: null
      importPolicy: {}
      name: "1.0.0"
  status:
    dockerImageRepository: ""
- apiVersion: v1
  kind: ImageStream
  metadata:
    creationTimestamp: null
    name: dparra0007-dynamic-config
  spec:
    tags:
    - annotations:
        openshift.io/imported-from: iaghcp-docker-technical-architecture.jfrog.io/dynamic-config:1.0.0
      from:
        kind: DockerImage
        name: iaghcp-docker-technical-architecture.jfrog.io/dynamic-config:1.0.0
      generation: null
      importPolicy: {}
      name: "1.0.0"
  status:
    dockerImageRepository: ""
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    creationTimestamp: null
    name: userapi
  spec:
    replicas: 1
    selector:
      deploymentconfig: userapi
    strategy:
      resources: {}
    template:
      metadata:
        creationTimestamp: null
        labels:
          deploymentconfig: userapi
      spec:
        containers:
        - image: dparra0007/userapi:{{TAG_SERVICE}}
          name: userapi
          ports:
          - containerPort: 3000
          resources: {}
          volumeMounts:
          - mountPath: /usr/src/conf
            name: userapi-config-claim0
          - mountPath: /usr/src/dynamic-conf
            name: userapi-dynamic-config-claim0
        - image: iaghcp-docker-technical-architecture.jfrog.io/static-config:1.0.0
          name: dparra0007-config
          env:
          - name: GLOBALCONF
            value: {{TAG_GLOBALCONF}}
          - name: SYSTEMCONF
            value: {{TAG_SYSTEMCONF}}
          volumeMounts:
          - mountPath: /usr/src/app/conf
            name: userapi-config-claim0
        - image: iaghcp-docker-technical-architecture.jfrog.io/dynamic-config:1.0.0
          name: dparra0007-dynamic-config
          env:
          - name: REMOTE_APPSETTINGS
            value: {{REMOTE_APPSETTINGS}}
          volumeMounts:
          - mountPath: /opt/app-root/src/conf/
            name: userapi-dynamic-config-claim0
        volumes:
        - name: userapi-config-claim0
          persistentVolumeClaim:
            claimName: userapi-config-claim0
        - name: userapi-dynamic-config-claim0
          persistentVolumeClaim:
            claimName: userapi-dynamic-config-claim0
    test: false
    triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
        - userapi
        from:
          kind: ImageStreamTag
          name: userapi:{{TAG_SERVICE}}
      type: ImageChange
  status: {}
- apiVersion: v1
  kind: ImageStream
  metadata:
    creationTimestamp: null
    name: userapi-db
  spec:
    tags:
    - annotations:
        openshift.io/imported-from: dparra0007/userapi-db:{{TAG_DB}}
      from:
        kind: DockerImage
        name: dparra0007/userapi-db:{{TAG_DB}}
      generation: null
      importPolicy: {}
      name: "{{TAG_DB}}"
  status:
    dockerImageRepository: ""
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    creationTimestamp: null
    name: userapi-db
  spec:
    replicas: 1
    selector:
      deploymentconfig: userapi-db
    strategy:
      resources: {}
    template:
      metadata:
        creationTimestamp: null
        labels:
          deploymentconfig: userapi-db
      spec:
        containers:
        - image: dparra0007/userapi-db:{{TAG_DB}}
          name: userapi-db
          ports:
          - containerPort: 27017
          - containerPort: 28017
          resources: {}
    test: false
    triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
        - userapi-db
        from:
          kind: ImageStreamTag
          name: userapi-db:{{TAG_DB}}
      type: ImageChange
  status: {}
- apiVersion: v1
  kind: Service
  metadata:
    creationTimestamp: null
    name: userapi
  spec:
    ports:
    - name: 3000-tcp
      port: 3000
      targetPort: 3000
    selector:
      deploymentconfig: userapi
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Service
  metadata:
    creationTimestamp: null
    name: userapi-db
  spec:
    ports:
    - name: 27017-tcp
      port: 27017
      targetPort: 27017
    - name: 28017-tcp
      port: 28017
      targetPort: 28017
    selector:
      deploymentconfig: userapi-db
  status:
    loadBalancer: {}
kind: List
metadata: {}
