version: '3'
services:
  userapi-db:
    build:
      context: ./userapi-db
    ports:
      - 27017:27017
      - 28017:28017
  userapi:
    build:
      context: ./userapi
    ports:
      - 3000:3000
    depends_on: 
      - userapi-db
