version: '3'
services:
  userapi-apigateway:
    build:
      context: ./userapi-apigateway
    environment:
      - GLOBALCONF=https://raw.githubusercontent.com/dparra0007/W53-STATIC-CONFIG-SETTINGS/master/env.sh
    ports:
      - 8080:8080
    depends_on:
      - userapi
  userapi-db:
    build:
      context: ./userapi-db
    ports:
      - 27017:27017
      - 28017:28017
  userapi-discovery:
    build:
      context: ./userapi-discovery
    ports:
      - 8761:8761
  userapi:
    image: composed-userapi
    # build:
    #   context: ./userapi
    ports:
      - 3000:3000
    links:
      - userapi-db
    depends_on: 
      - userapi-db
      - userapi-config
      - userapi-dynamic-config
    volumes:
      - ${PWD}/userapi-config:/usr/src/conf
      - ${PWD}/userapi-dynamic-config:/usr/src/dynamic-conf
  userapi-config:
    image: iaghcp-docker-technical-architecture.jfrog.io/static-config:1.0.0
    environment:
      - GLOBALCONF=https://raw.githubusercontent.com/dparra0007/W53-STATIC-CONFIG-SETTINGS/master/env.sh
      - SYSTEMCONF=https://raw.githubusercontent.com/dparra0007/W53-STATIC-CONFIG-SETTINGS/userapi/env.sh
    volumes:
      - ${PWD}/userapi-config:/usr/src/app/conf
  userapi-dynamic-config:
    image: iaghcp-docker-technical-architecture.jfrog.io/dynamic-config:1.0.0
    environment:
      - REMOTE_APPSETTINGS=https://raw.githubusercontent.com/dparra0007/W53-USERAPI-CONFIG/master/default.json
    volumes:
      - ${PWD}/userapi-dynamic-config:/opt/app-root/src/conf/
