version: '3'
services:
  userapi-apigateway:
    build:
      context: ./userapi-apigateway
    environment:
      - SERVICE1=userapi
    ports:
      - 8080:8080
    depends_on:
      - userapi
  userapi-db:
    build:
      context: ./userapi-db
    ports:
      - 27017:27017
      - 28017:28017
  userapi-discovery:
    build:
      context: ./userapi-discovery
    ports:
      - 8761:8761
  userapi:
    build:
      context: ./userapi
    ports:
      - 3000:3000
    links:
      - userapi-db
      - userapi-discovery
    depends_on: 
      - userapi-db
      - userapi-discovery
      - userapi-config
    volumes:
      - ${PWD}/userapi-config:/usr/src/conf
  userapi-config:
    image: dparra0007/static-config:20180522-2
    environment:
      - GLOBALCONF=https://raw.githubusercontent.com/dparra0007/W53-STATIC-CONFIG-SETTINGS/master/env.sh
      - SYSTEMCONF=https://raw.githubusercontent.com/dparra0007/W53-STATIC-CONFIG-SETTINGS/userapi/env.sh
    volumes:
      - ${PWD}/userapi-config:/usr/src/app/conf
